### ISSUE TITLE
可以控制白边的生成么

### ISSUE THREAD

**Issue by crperlin** [aralejs/qrcode#21]
就是二维码周边的白色边框。。。

**Comment by hotoo** [comment]
```css
div { background-color: #fff; padding: 5px; }
```
